name: OpenStreetMap e Brezhoneg
description: 'test map'
attribution: 'CC-BY-SA OSM-BZH'
scale: 1
metatile: 2
bounds: &world
  - -180
  - -85
  - 180
  - 85
center:
  - -2.96
  - 48.03
  - 8
format: 'png'
interactivity: false
minzoom: 4
maxzoom: 18
srs: "+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0.0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over"


_parts:
  # default values used by layers
  extents: &extents
    extent: *world
    srs-name: "3857"
    srs: "+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0.0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over"
    class: ''
    status: 'on'

  extents84: &extents84
    extent: *world
    srs-name: "WGS84"
    srs: "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs"

  osm2pgsql: &osm2pgsql
    type: "postgis"
    dbname: "osm"
    key_field: ""
    geometry_field: "way"
    extent: "-20037508,-20037508,20037508,20037508"
    host: db.openstreetmap.world
    user: osmbr
    password: m4d31nbr31zh
    asynchronous_request: 'true'
    max_async_connection: '4'


Stylesheet:
  - test.mss


# the layers
Layer:

  - id: land_low
    geometry: polygon
    <<: *extents
    Datasource:
      file: /data/project/styles/data/simplified-land-polygons-complete-3857/simplified_land_polygons.shp
      type: shape
    properties:
      minzoom: 0
      maxzoom: 10


  - id: land_high
    geometry: polygon
    <<: *extents
    Datasource:
      file: /data/project/styles/data/land-polygons-split-3857/land_polygons.shp
      type: shape
    properties:
      minzoom: 9
      maxzoom: 20


  - id: roads_low
    geometry: linestring
    <<: *extents
    Datasource:
      <<: *osm2pgsql
      table: |-
        (SELECT
          osm_id,
          way,
          COALESCE(highway, railway) AS type, 
          0 AS tunnel,
          0 AS bridge,
          access,
          'fill' AS render, 
          CASE 
              WHEN highway IN ('motorway', 'trunk') THEN 'motorway' 
              WHEN highway IN ('primary') THEN 'mainroad'  
              WHEN railway IN ('rail') THEN 'railway'
          ELSE 'other'
          END AS stylegroup 
        FROM planet_osm_line 
        WHERE
          highway IN ('motorway', 'trunk', 'primary')
          OR railway IN ('rail')
          AND (tunnel IS NULL OR tunnel = 'no') 
          AND (bridge IS NULL OR bridge = 'no') 
        ORDER BY z_order  ) AS roads_low
    simplify_geometries: 'true'
    properties:
      minzoom: 5
      maxzoom: 20

